### ISSUE TITLE
Option - 'dump all'

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#13]
An option for doing a ‘dump all’ on the public interface (like fkie). Do not include rosout & service loggers etc

**Comment by jihoonl** [comment]
We may also exclude these from image topic

/compressed
/compressed/parameter_descriptions
/compressed/parameter_updates
/compressedDepth
/compressedDepth/parameter_descriptions
/compressedDepth/parameter_updates
/theora
/theora/parameter_descriptions
/theora/parameter_updates

**Comment by piyushk** [comment]
I'll take this one. I know I am going to use 'dump all'/'pull all' quite a bit before I figure out all the kinks in my system. Since I already have it working in simulation, I expect no clashes.

Here are my current thoughts on it:
1) This option can be enabled via a service
2) Continuously poll for all available topics and keep pushing them out to the public interface. Would it make sense to do this in the cleanup thread?

I would recommend putting in /compressed and /theora. I prefer to use compressed over wifi. We can leave out rosout, service loggers and dynamic reconfigure (i.e. the parameter_descriptions and parameter_updates). It might also make sense to leave out /tf, as I think that needs to be handled separately.

**Comment by stonier** [comment]
Some ideas:
- A service sounds good.
- Might be worth putting in flags in the service request along with reasonable defaults so you can 'customise' your dump all a bit.
- Maybe also a manually set blacklist as well? i.e. dump all except foo and bar
- Cleanup thread is right...we're actually thinking that should be better named a 'watcher' thread for some of the ideas we have.

**Comment by jihoonl** [comment]
Yeah. Cleanup thread meant to be a thread to "clean up" the unresponsive nodes or topics. Since it gets more duty, we should rename it as Daniel suggested.

**Comment by piyushk** [comment]
Sounds good. I think this gives me enough information to start with. I'll get back once I have an implementation ready.

**Comment by piyushk** [comment]
So I put in a few hours into this, and an implementation is up in my branch. It should be easy to test this branch through a second ROS workspace, and my rosinstall file. I still need to figure out the semantics a bit more (and some more testing). In the notes below, I'll talk in terms of topics below, but an untested parallel for services exists

Here are some basic notes:
- I have create a master_sync style whitelist for named topics. You can now push regex based named topics to the public interfaces:
  - rosservice call /gateway/request add_named_topics ['/chatter','node1/*']
- The "cleanup" thread looks at the whitelist, and pushes/removes topics from the public interface
- Topics can be removed
  - rosservice call /gateway/request remove_named_topics ['/chatter']
- The make_all_public service simply pushes ".*" into the whitelist
  - rosservice call /gateway/request make_all_public []
  - This is same as calling rosservie call /gateway/request add_named_topics ['.*']
- Dump all can be removed
  - rosservice call /gateway/request remove_all_public
- To prevent everything from going into the public api, there is a separate blacklist. Named topics are only put into the public api if they are in the whitelist, and not on the blacklist. Currently the blacklist is exposed as a ros parameter, and defaults to some appropriate topics (as discussed above). 

Although we can expose the blacklist as a service as well, I am wondering if the having a separate whitelist and blacklist for topics might be overkill. Additionally the semantics need to be clear. For instance:
- rosservice call /gateway/request remove_named_topics ['/chatter'] - This will remove /chatter from the whitelist, but won't blacklist it. This means that if any other regex matches /chatter, the topic will still get published.

Do you guys have suggestions for a better solution?

**Comment by stonier** [comment]
Thoughts:
- Using regex patterns is great.
- A blacklist as a ros parameter also works for me, I don't have any use cases where it should be dynamic, so let's only implement it if we need it.

**Comment by piyushk** [comment]
Thanks for the feedback. The implementation is ready for testing. Instructions are available in the tutorial: http://redmine.robotconcert.org/projects/multimaster/wiki/Gateway_Development

I recommend testing using a 2nd workspace with this rosinstall file: https://raw.github.com/robotics-in-concert/rocon_multimaster/master/rocon_multimaster_piyushk.rosinstall

**Comment by piyushk** [comment]
I also think a set/get service for the public topic whitelist might be more powerful than the current add/remove. There is currently no way to get the whitelist.

**Comment by stonier** [comment]
Sorry for the delay, was hacking t2 for a demo today. 

Just took your code for a road test - works great. I like the named approach, simplifies flipping alot and useful for 90% of cases. Nice to have the triples still there though, just for the corner case. 

A getter for the list would certainly be useful. Though I'm not sure about a setter since we can't guarantee atomicity of the get/set commands which makes things unclear i.e. by the time your fill out your 'set' and send it, you might already be acting on old information.

If we split up services, adding and removing a named topic should usefully return the list of regex pattern's it is currently using.

**Comment by piyushk** [comment]
Excellent point about the atomicity of get/set commands. Didn't think about
that.

Let's definitely have the triples. I think you're right that the finer
control might be useful in certain cases. At the same time, I would
recommend making the following name changes throughout the codebase:
topic -> topic_triple OR topic_uri
service -> service_triple OR service_uri
named_topic -> topic
named_service -> service
My rationale behind this is that most of the ROS community is unaware of
individual uris, and are only familiar with named channels.

Also, your last comment makes me vote in approval of splitting services. It
might make more sense.

**Comment by piyushk** [comment]
An implementation has now been integrated.
