### ISSUE TITLE
Need to know when the topics are connected(or flipped)

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#140]
In order to use navigation using shared map among clients, each clients are waiting to the map topic establishes.

To have better work-flow in solution-wise, it would be great to know when all topics are connected and when the app is ready to go.

**Comment by stonier** [comment]
You would like a publisher on the gateway that announces something like state changes to the local system?

**Comment by stonier** [comment]
getNumSubscribers/getNumPublishers usually works for this kind of thing. For more complicated scenarios we usually use the master's slave api.

The problem here is that probably web apps don't have this api. Sounds like it needs it. 

Anyway, if the problem would be solved by one of these two functions the transport implementation is where it should be added. Putting it in the gateway is adding a second way to deal with a problem that makes a small use group happy.
