### ISSUE TITLE
Robustness to hub losing all information?

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#177]
Let's say the hub machine loses power (or the hub needs to be restarted from scratch). As of right now, the gateways will re-register with the hub, but will not attempt to re-sync the public interface. How important would be this robustness feature?

I'll also have to think about whether this affects flipped or pulled connections or not.

**Comment by piyushk** [comment]
Here's another thing to consider. Let's say we add the ability for hubs to drop gateways if they become unreachable. In this case, the hub may remove all information about the gateway. This becomes another instance where it is necessary to sync up information about the gateway.

**Comment by stonier** [comment]
My two cents:

Hubs going down - **low priority**. The redis server is rock solid and should be on the wired backbone of the lan so for the moment, it's probably a 1 in 10,000 case to handle. The robots going in and out of range, crashing or getting turned off is much more important. See below.

Syncing gateway information on the hub - yeah as this is relevant to disappearing robots. As you've noticed, the advertisments on the hub keep getting advertised whether the robot is or not there. You could get the hub to do the housekeeping itself, but even then, gateways should always check the result of pulling from other gateways because they can never exactly guarantee that the hub's information is synced with the availability of another gateway.

So, should the hub housekeep? I'd actually be inclined to say no and instead leave the information there (it's all uniquely represented by uuid's and doesn't take alot of space), but add a field to what is stored about a gateway on the hub indicating if the hub is contactable or not. That could be binary to start off with and more informative later.

The gateways should of couse then sync properly. Checking and clearing upon startup, closure and re-establishing information on reconnects.

**Comment by piyushk** [comment]
let's discuss hub housekeeping when we talk about disconnection policies later this week. I'll work on this issue report once we have a plan.

**Comment by stonier** [comment]
:+1:

**Comment by stonier** [comment]
Aborting for now - discussed in our  [wireless disconnection policies](https://docs.google.com/document/d/1ENqBxEagX2EtLFAXyDL1ULDxoFd2biRB8D5KOhwQm6k/edit?usp=sharing) hacking. To solve it we should probably use redis replication.
