### ISSUE TITLE
Gracefully handle zeroconf failures

### ISSUE THREAD

**Issue by siapapa** [robotics-in-concert/rocon_multimaster#181]
The zeroconf error with the massage as "Zeroconf: failed to create an avahi client." might be solved by http://wiki.ros.org/zeroconf_avahi/Troubleshooting

When you apply the solution, then you need to reboot your robot to fix the problem.

**Comment by stonier** [comment]
![zeroconf_avahi_error](https://f.cloud.github.com/assets/687378/1235258/b8d9fd02-29a0-11e3-9d4d-6ad645e20fc2.png)

**Comment by stonier** [comment]
Gateway should bug out more gracefully than this when zeroconf fails to create a client. Some notes...
- Zeroconf if it's bugged out:
  - Informs you by log message
  - Doesn't provide any programming handle to check bugged out status, then dies.
- HubDiscovery client doesn't catch the ServiceException that comes its way.

Clean this up better. It's getting the service exception because zeroconf's node crashed without cleaning up the services properly.
