### ISSUE TITLE
Gateway hub sidekick

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#185]
This is an action in the [wireless disconnection policies](https://docs.google.com/document/d/1ENqBxEagX2EtLFAXyDL1ULDxoFd2biRB8D5KOhwQm6k/edit?usp=sharing).

Probably add functionality into `hub.py` (same script that starts the hub) with a gateway ping to:
- [x] establish some connection statistics.
- [x] cleanup dropped gateway information (refer to info in #182).

**Comment by stonier** [comment]
Useful info for connection statistics:
- When unavailable, time since last seen, with an upper limit (gathered by the hub sidekick)
- wireless/wired (information sent from the gateway)
- wireless signal strength (information sent from the gateway)
- Can we get ping latency times (averages/moving averages)?

**Comment by stonier** [comment]
How should we expose this? By ros api or by putting it on the redis server itself?

**Comment by piyushk** [comment]
My vote would be to put it on the Redis server itself. The ROS system does not really need to know about this.

**Comment by piyushk** [comment]
I've looked at the above points. Here's my take on how this information can be collected:

Information collected by hub sidekick (and placed on redis server):
1. Ping latency times. We can collect this information by parsing the output of the ping command we use to find out if a hub is active.
2. When a gateway is unavailable for 30s, our current policy is to remove it from the hub. If we maintain information such as "when unavailable, time since last seen", then should we stop removing it and mark it as unavailable and remove until the upper limit is achieved? I am not entirely sure what a use case for this information would be.

Information collected by the gateway:
1. Wireless or wired connection. If wireless, then signal strength and data transfer rate (both reported by iwconfig). We'll need a wrapper around iwconfig. The closest thing that is available is: https://pypi.python.org/pypi/python-wifi, but it introduces an external dependency that is not available through debs.
2. The gateway will have to determine what network interface is being used. We can do a a few things to auto-detect it, but is it easier to make it a user requirement to set an appropriate environment variable (ROS_INTERFACE)? My problem with auto-detection is that there is no way to be sure which interface is being used if 2 are connected, and the ROS_IP has been set to a resolvable hostname.

I'll wrap these up on Wednesday and Thursday (11/6-11/7).

:neckbeard:

**Comment by stonier** [comment]
Information collected by hub sidekick (and placed on redis server):
1. ok
2. yes - after 30 sec, mark it as unavailable with a time last seen. Maybe set an upper limit configurable by parameter, 2hrs? After which it cleans it from the redis server.

Information collected by the gateway:
1. Can we ros-package python-wifi like we package redis in rocon_multimaster?
2. The gateway gets a hub ip when auto-discovering the hub, can it match the ip of the hub with the interface on the machine?

**Comment by piyushk** [comment]
I don't see any reason why we should not be able to package python-wifi. I will look into it.

Matching the hub IP to which local interface is being used will be messy, but might be possible. I will explore this.

**Comment by stonier** [comment]
@piyushk What kind of variance/deviation does mdev represent?

**Comment by piyushk** [comment]
It's the mean absolute deviation. These 4 values are returned by ping, and I use short bursts of 5 messages every time I ping a machine.

**Comment by piyushk** [comment]
I just realized that I forgot to add a time_last_seen when the gateway is unavailable. I will add that now.

**Comment by stonier** [comment]
:neckbeard:
