### ISSUE TITLE
Gateway info on the hub

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#19]
- hash id’s for unique identification of gateways - we need to keep associating them even if they go in and out of wireless range
- each gateways’ zeroconf name
- suggested string name (for human readability)
- unique string name (for human readability)(generated by hub server program)

**Comment by stonier** [comment]
Jihoon's implemented an indexer which can be pulled by the clients so they can themselves generate their own unique string names - for the respective hub. So, we don't need suggested string names.

We also don't need zeroconf names since we're not using them at the gateways.

Hash id's are meaningless now we can track by unique strings names.

So...done!
