### ISSUE TITLE
Network health monitoring

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#20]
Really rough idea - probably there is tools that can help us do this.
-  gateways ping the redis server every 1s (how to ping? incremental counter?)
-  hub server program polls every 1s looking for redis server changes
  1. associates a local timestamp with new pings
  2. generates a time since last seen for each gateway
-  maybe also checks if it can connect to each ip (what does connect mean)
-  some statistics on the connection, e.g. % of time down, mean downtime period...
-  is it better to use something that already does all this for us?

**Comment by piyushk** [comment]
I'll try to summarize the current status as I see it:
- Gateways detecting hub failures: 
  - Gateways can currently detect hub failure if the hub goes down, and the network connection to the machine exists. 
  - If the network goes down, the gateways currently do not detect that hub went down.
  - Interestingly enough, the rocon_hub_client is using an independent mechanism for detecting if the hub is still up, by attempting to instantiate a new redis connection every 0.5 seconds. It is able to detect when the hub goes down due to network issues.
- Hubs do not detect if a gateway goes down. They continue providing information about remote gateways irrespective of status

I am not sure what pt 3 in the original issue report means. I can't seem to find a ready made solution for this (pt 4, pt 5), though my khowledge about python modules is limited For now I think I am going to come up with something basic, which we can switch to a readymade solution once available.

**Comment by stonier** [comment]
Closing this and will re-open a new issue based on the [wireless disconnection policies](https://docs.google.com/document/d/1ENqBxEagX2EtLFAXyDL1ULDxoFd2biRB8D5KOhwQm6k/edit?usp=sharing) doc.
