### ISSUE TITLE
Flipping an action server

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#208]
I flipped an application server. The server side seems fine:

```
[INFO] [WallTime: 1383941883.623220] [149.680000] Gateway : sending flip request [orchestrator][action_server][/robot1/move_base][/robot1/move_base]
```

The client side does not. I was under the impression that it should read action_client below. Was this behavior changed at some point time?

```
[INFO] [WallTime: 1383941883.624021] Gateway : received a flip request [robot1][subscriber][/robot1/move_base/goal][/robot1/move_base]
[INFO] [WallTime: 1383941883.627180] Gateway : received a flip request [robot1][subscriber][/robot1/move_base/cancel][/robot1/move_base]
[INFO] [WallTime: 1383941883.630059] Gateway : received a flip request [robot1][publisher][/robot1/move_base/status][/robot1/move_base]
[INFO] [WallTime: 1383941883.632887] Gateway : received a flip request [robot1][publisher][/robot1/move_base/feedback][/robot1/move_base]
[INFO] [WallTime: 1383941883.636602] Gateway : received a flip request [robot1][publisher][/robot1/move_base/result][/robot1/move_base]
```

**Comment by stonier** [comment]
client = receiver of the flip request?

From the user perspective, the flipping gateway flips an action server, even though under the hood it's actually just flipping pubs and subs. On the receiving side, it looks like it's just getting a set of pubs/subs. I visited this a while ago and wondered if I should put in that whole abstraction layer to make it look like actions. Is this what you are talking about?

I decided against worrying about it at the time, because I didn't have an urgent use case that needed any simplifications for interactions (i.e. handling ros api) with the user on the receiving side.

**Comment by piyushk** [comment]
Yes, that is what I was talking about. 

I was under the impression that this feature had already been implemented, and was surprised that it got removed. It's not anything urgent.

**Comment by stonier** [comment]
Never got implemented because it wasn't functionally required. I did think about going back and doing it in the name of consistently abstracting the action stuff, but I didn't really have a need, nor needed to even introspect it like that much. If you need it, let me know.
