### ISSUE TITLE
Self-cleanup connections if hub is gone

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#213]
When hub is gone, it should clean up all connections and apps related to the hub which has left.

**Comment by stonier** [comment]
For reference, this is when the gateway tries to take some action on the hub like cleaning flips, and the hub is no longer there. 

**Scenario**

It came up when shutting down the concert. The concert sent out stop signals to the app managers and the app managers' gateways tried to clean up, but flopped when they could not find the hub.

**Comment by jihoonl** [comment]
How to replicate.
1. rocon_launch concert_tutorial tutorial.concert
2. kill concert terminal

Then you will see some clients have not stopped app.

**Comment by piyushk** [comment]
We need to be a bit careful depending on how the hub has "gone". It might be a network outage.

Once #215 is resolved, the gateway will continue to operate once we have difficulty connecting to the hub (i.e. Hub connected = false). Its OK to remove all the connections as long as we are sure we can synchronize them back again once the hub is found again. Since the hub only removes this gateway after 2 hours (https://github.com/robotics-in-concert/rocon_multimaster/commit/e207a9efcce41461ffa64eb687ab45eda8b59818), flip requests are not currently resent if the gateway comes back online during these 2 hours.

**Comment by piyushk** [comment]
@stonier @jihoonl What's the progress on the demo?

Let me know whenever you guys have time to discuss this issue.

**Comment by stonier** [comment]
Planned to write you an email exactly today! Will do so and lets follow up on gchat/hangout.

**Comment by piyushk** [comment]
@jihoonl @stonier 

Could one of you explain to me what went wrong here. The gateway does try to clean up connections if a hub is gone, however it is only getting called occasionally. Synchronization seems to be working correctly irrespective of whether the connections get thrown out or not. I will be setting up a separate issue report for that. If that was not the problem here, please let me know. I will start debugging that issue soon.

**Comment by piyushk** [comment]
Related issue report: https://github.com/robotics-in-concert/rocon_multimaster/issues/229

**Comment by stonier** [comment]
Test:

Local (port 11311) - hub + gateway + talker

```
> roslaunch rocon_gateway_tests local_wireless.launch
```

Remote (port 11312) gateway

```
> roslaunch rocon_gateway_tests remote_client.launch
```

The chatter topic gets flipped in from local to remote. On the remote machine, 

```
$ rostopic list
/flipped_chatter_from_local
/gateway/force_update
/gateway/gateway_info
/remote_gateway8613e1fd9f444f5bb6e8318b69cd2260/app_list
/remote_gateway8613e1fd9f444f5bb6e8318b69cd2260/runnable_app_list
/rosout
/rosout_agg
/zeroconf/lost_connections
/zeroconf/new_connections
```

and in gateway_info:

```
  Flipped in Connections
       : local_gatewayb5edd29af58b4d85a5b82fb005e58424-/flipped_chatter_from_local-publisher-/talker_snorriwork64_5046_5561430740367798471
```

Then ctrl-c the roslauncher on the local side (bring down hub, gateway and talker). Then in the remote, you can still find the topic, both in the flipped in connections under gateway_info and also in rostopic info /flipped_chatter_from_local

**Comment by stonier** [comment]
This is no longer a high priority - found a good way to stop apps properly without having to do hackery cleanup.

Nonetheless, it's a loose end. I wouldn't commit time on it though until we absolutely need to.

**Comment by piyushk** [comment]
Thanks for pointing this out. As it turns out, when a gateway loses connectivity with the hub, we abandon pulled connections, but not flipped in connections.

The synchronization issue is this: Simply removing the flipped-in connection will not work, as the other side won't know to send a flip request if this was a network outage, and the gateway-hub connection comes back online. Re-pulling an abandoned pull is far more obvious. 

Setting a "resend_flips" bit on the hub seems like a logical solution.
