### ISSUE TITLE
SubscriberProxy dependency on rospy.Duration

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#242]
Another re-occurrence of https://github.com/robotics-in-concert/rocon_multimaster/issues/191

I forgot to flip /clock to one of my gateways in my simulated concert domain, and ended up in bizzare problems in the app manager because of this line. https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_manager/src/rocon_app_manager/rapp_manager.py#L638

I can see why it might actually be beneficial to have rospy.Duration ad a parameter to the SubscriberProxy call, but it is a bad idea to use in rocon code. Maybe add functionality for a parallel wall_timeout parameter with wall time in float in the SubscriberProxy class?

**Comment by stonier** [comment]
I'm a bit naive about these time related gazebo on drugs issues. Looking at https://github.com/robotics-in-concert/rocon_multimaster/blob/hydro-devel/rocon_utilities/src/rocon_utilities/ros_utilities.py#L135
is the problem actually anything to do with the duration call?

Looks like it's either (or probably both) due to rospy.Rate's sleep getting diminishing into monumumental insignificance or the rospy.Time.now() getting accelerated to the point where the timeout is reached faster than it should. Is this your expectation as well?

I was just implementing a non-blocking pub-sub 'service pair' today and while doing the wait_for_xxx function, noticed ken's wait_for_service code strictly uses python's time and doubles everywhere. I should switch my code to do that. There was no special reason for using the duration's there.

**Comment by piyushk** [comment]
I think you're correct. I didn't look at the actual code. The duration call made me realize that ros time was being used in the code. 

If sim time is active, and no clock messages are received, rostime in both C++ and python returns 0, and time does not move (and I believe r.sleep never returns, though the timeout check will not work as well). If sim time is moving, things are typically not too bad.

**Comment by stonier** [comment]
Got it. I'll update the internals of that function then.

**Comment by stonier** [comment]
Looks like the service pair client is ok, no need to switch there.
