### ISSUE TITLE
terminator warning shows even if gnome-terminal is used.

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#246]
```
You are using an esoteric unsupported terminal [terminator]
 --> falling back to 'gnome-terminal'
```

**Comment by stonier** [comment]
This is not expected behaviour?

**Comment by jihoonl** [comment]
I think that warning only happen when I use terminator. It showed even if I used gnome-terminal instead of terminator.

**Comment by stonier** [comment]
It is detecting the system-default setting for your shell (cant remember how, but its in the code). So it doesn't matter what shell you are in when you are starting rocon_launch.

This is necessary because you can start rocon_launch without starting in a gnome-terminal, terminator or konsole.

I don't know if you can sniff what shell you are currently in or whether its worth implementing it as it doesn't seem to be a really necessary thing. If it's annoying you greatly, scratch the itch ;)
